### PR TITLE
Fixed get/set accessor methods for MysteryBoxInfo.as

### PR DESCRIPTION
**Pull request by kaos00723**

### CODE REVIEW

**Comment by cp-nilly** [comment]
Interesting. Not having the return type broke the functions?

**Comment by kaos00723** [comment]
Not sure if it actually broke them in-game but you'll get errors in IntelliJ after opening it and this is the fix for those errors.

**Comment by cp-nilly** [comment]
Since this seems like a general issue, you mind fixing up FortuneInfo in the same way? Also if you have time, looking up the object type and using that instead of \* would be preferred.

**Comment by kaos00723** [comment]
Sure thing, will take a look.

**Comment by kaos00723** [comment]
We receive an error in MysteryBoxSelectEntry.as for (saleAmount, saleCurrency, priceAmount, priceCurrency) if the "*" isn't used for those. The rest have been updated.

**Pull request merged**
